FROM node:13.12.0-alpine3.11
WORKDIR /usr/src/app
COPY package*.json ./
COPY server.js ./ 
COPY wait-for-it.sh ./ 
COPY ./app/config ./app/config 
COPY ./app/controllers ./app/controllers 
COPY ./app/models ./app/models 
COPY ./app/resources ./app/resources
COPY ./app/routes ./app/routes 
COPY ./app/utils ./app/utils
COPY ./app/test ./app/test
RUN apk add --no-cache --upgrade bash
RUN ls -laRt ./
RUN npm install
EXPOSE 8080
ENTRYPOINT ["node", "server.js", "--force_sync", "true"]


