FROM node:bookworm-slim

WORKDIR /usr/src/app
COPY package*.json ./
COPY server.js ./ 
COPY wait-for-it.sh ./ 
COPY ./app/config ./app/config 
COPY ./app/controllers ./app/controllers 
COPY ./app/models ./app/models
COPY ./app/routes ./app/routes 
COPY ./app/utils ./app/utils
COPY ./app/test ./app/test
COPY ./app/locales ./app/locales
RUN ls -laRt ./
RUN npm install
EXPOSE 8080
ENTRYPOINT ["node", "server.js", "--force_sync", "true"]


