version: "3.8"
services:
  db:
    build: ./react-crud-web-api
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: doer-db-user
      MYSQL_PASSWORD: ThePassword
    restart: always
    container_name: doer_db
    networks:
      - doer_db_network 

  web:
    build: ./nodejs-express-sequelize-mysql
    container_name: doer_web
    ports:
      - "8080:8080"
    networks:
      - doer_db_network
    depends_on:
      - db
    command: ["./wait-for-it.sh", "doer_db:3306", "--", "node", "./server.js"]
    restart: on-failure

networks:
    doer_db_network:
      name: doer_network

