version: "3.8"
services:

  db:
    build:
      context: doer-mysql-container
      dockerfile: Dockerfile.doer_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: doer-db-user
      MYSQL_PASSWORD: ThePassword
    restart: always
    container_name: doer_db
    image: doer_db:0.0.2
    networks:
      - doer_db_network
      
  web:
    build: 
      context: ./react-crud-web-api
      dockerfile: Dockerfile.doer_web
    container_name: doer_web
    image: doer_web:0.0.2
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - doer_db_network
    restart: on-failure
    links:
      - api 

  api:
    build: 
      context: ./nodejs-express-sequelize-mysql
      dockerfile: Dockerfile.doer_api
    container_name: doer_api
    image: doer_api:0.0.2
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - doer_db_network
    restart: on-failure

networks:
    doer_db_network:
      name: doer_network

