services:
  db:
    container_name: doer_db
    build: 
      context: ./
      dockerfile: Dockerfile.doer_db
   #   platforms:
   #     - "linux/arm64"
    image: doer_db:0.4.0 
    platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./app/config/01_sql.sql:/docker-entrypoint-initdb.d/initdb.sh
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pg-user
      - POSTGRES_DB=doerdb
    restart: always
    networks:
      - doer_db_network

  api:
    build: 
      context: ./
      dockerfile: Dockerfile.doer_api
      #platforms:
      #  - "linux/arm64"
    container_name: doer_api
    platform: linux/amd64
    image: doer_api:0.14.2
    entrypoint: ./wait-for-it.sh doer_db:5432 --strict -- node server.js --force_sync true
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - doer_db_network
    restart: on-failure

networks:
    doer_db_network:
      name: doer_network

